require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'schooltime' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'


  pod 'RNSound', :path => '../node_modules/react-native-sound'


  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'



  pod 'RNSecureStorage', :path => '../node_modules/rn-secure-storage'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'ReactNativeGetLocation', :path => '../node_modules/react-native-get-location'

  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  target 'schooltimeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end